# docker-compose.yml
version: "3.8"

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  awscli:
    image: amazon/aws-cli
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_ENDPOINT_URL=http://localstack:4566
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      aws --endpoint-url=http://localstack:4566 s3 mb s3://bff-handler-main;
      aws --endpoint-url=http://localstack:4566 s3api put-bucket-acl --bucket my-bucket --acl public-read;
      sleep 5;
      aws --endpoint-url=http://localstack:4566 s3 mb s3://bff-handler-fallback;
      aws --endpoint-url=http://localstack:4566 s3api put-bucket-acl --bucket my-bucket --acl public-read;
      tail -f /dev/null
      "
    depends_on:
      - localstack
