name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Check Destroy Flag
        id: check-destroy
        run: bash ../bash/check-destroy.sh
        working-directory: ./terraform

      - name: Setup Node.js
        if: env.DESTROY == 'false'
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: 'app/package-lock.json'
      
      - name: Install Dependencies
        if: env.DESTROY == 'false'
        run: npm ci
      
      - name: Run Unit Tests
        if: env.DESTROY == 'false'
        run: npm run test
      
      - name: Run End-to-End Tests
        if: env.DESTROY == 'false'
        run: npm run test:e2e
        
      - name: Cache Node Modules
        if: env.DESTROY == 'false'
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('app/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-